Purr Music Player
================
:Author:    Alexander Schwoch
:Email:     vashsan@gmail.com
:Date:      2013-03-09
:Revision:  0
:toc:

== Purpose

I am dissatisfied with a lot of music players. Those that exist run
either on Linux or Windows. Those that run on both are unstable or do
not comfort my requirements for a small, fast, decent player.

I do not need visualizations nor skins nor a lot of the other fancy
stuff out there. It shall play MP3 and maybe OGG thats it, and that
is what you shall find here.


== License

Still need to figure it out. It will contain these terms:
* You may distribute the unmodified source files and binary packages
 free of charge.
* You may change the source files for your private and non commercial
  purposes without restriction.
* If you want to distribute changed sources or binaries you must
  - do it free of charge.
  - attribute the original work to the authors - that is all contributors
    who can be summarized as "The Purr Developer Community".
  - release the changes to the public.
* You must accept that there are no warranties tied to the sources or
  binaries. This means that any harm or error concerning this piece of
  software comes unintentionally and if you use the software you do it
  at your own risk.


== Installation

.Windows
If you got hold of a zip or 7z file then it contains the purr.exe
and all necessary DLLs. See the <<sec-releases,Releases section>>
for these files. Just extract the content to any place you like, just
do not share the program directory with other data or programs. I
recommend to place a shortcut to the executable on your desktop, the
start menu or task bar for convenience. But this is up to you. A desktop
link can be created by dragging purr.exe to the desktop while holding
the ALT-key.

.Linux
For the time being you will need to build the player yourself, see
instructions below. If you created or want to create a package for
a distribution let me know so I can add it here.

.Mac
You need to figure out yourself if this works, however by following the
build instructions you might succeed. There will be no official support
for version 1.0 though. Maybe later.

.Building the player
The source are available at https://github.com/VashSan/purr[github].

You need the http://qt-project.org/[Qt framework 5.0.1]. I guess the easiest
way is to download it, start QtCreator open the project file and and hit
the build button - for me this works under Windows and Linux. If you prefer
a different build process you will need to figure it out yourself.


== Contributing

As you may have noticed you will find the sources on github. I will add some
coding guidelines, however I will leave this for now. Have a look at the
source and be patient: I am still thinking about it.

The sources are available for anyone to read since Purr is open source.

The organization is done via
https://trello.com/board/purr-player/512d0240c91efcb743011e60[Trello] though.


[[sec-releases]]
== Releases

[grid="rows",format="csv"]
[options="header",cols="<,<,>m,<"]
|===========================
Version,Platform,File,Size,Download
Alpha 1,Windows,purr-alpha.zip,27.6 MB,https://mega.co.nz/#!OYExQTpL!box_aGMpDrPJcCZFhB3M_i_owegKdmr0iPYXIqmS8Zk[Mega]
|===========================

